// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LL_ActorChoicesMV","status":true,"description":"アクターを選択するプラグインコマンドを実装します。","parameters":{"selectActorListMasters":"[]","cancelLabel":"キャンセル","cancelPosition":"bottom"}}
];
